version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./satellite.db
      - LOG_LEVEL=INFO
    volumes:
      - ./app:/app/app
      - ./db:/app/db
      - ./models:/app/models
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=satellite_db
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  models:
    driver: local

# Optional development configuration
x-dev:
  &dev
  build:
    context: .
    dockerfile: Dockerfile
    args:
      - DEV=true
  environment:
    - DATABASE_URL=postgresql://postgres:postgres@db:5432/satellite_db
    - LOG_LEVEL=DEBUG
    - PYTHONPATH=/app
  volumes:
    - ./app:/app/app
    - ./db:/app/db
    - ./models:/app/models
    - ./tests:/app/tests
  command: poetry run uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

services:
  app-dev:
    <<: *dev
